export const STRINGS = {
  panel: {
    title:              'JobLens',
    tabs: {
      score:     'Score',
      recruiter: 'Recruiter',
      match:     'Match',
    },
  },
  score: {
    label:        'Opportunity score',
    analyzing:    'Analyzing opportunity…',
    enriching:    'Enriching data…',
    partialNote:  'Some signals unavailable',
  },
  signals: {
    title:        'Signals',
    timing:       'Hiring activity',
    competition:  'Applicants so far',
    response:     'Company response rate',
    match:        'Your resume match',
    company:      'Company rating',
    recruiter:    'Recruiter activity',
    funding:      'Funding stage',
    jobPosted:    'Job posted',
    competitionLevel: 'Competition level',
  },
  recruiter: {
    title:        'Best contact targets',
    approach:     'Recommended approach',
    loading:      'Finding the right contacts…',
    notFound:     "Couldn't find recruiter on LinkedIn",
    limitReached: 'free lookups used this month',
    cta:          'Draft my message',
  },
  match: {
    title:        'Your resume match',
    matched:      'Matched skills',
    missing:      'Missing',
    partial:      'Partial',
    upload:       'Upload your resume to see your match score',
    update:       'Update my resume',
  },
  draft: {
    title:        'Your LinkedIn DM to',
    generating:   'Drafting your message…',
    copy:         'Copy',
    copied:       'Copied',
    regenerate:   'Regenerate',
    edit:         'Edit',
    tones: {
      professional: 'Professional',
      casual:       'Casual',
      concise:      'Concise',
    },
  },
  errors: {
    scrapeFailed:    "Couldn't read this page. Try refreshing.",
    enrichFailed:    'Some signals unavailable',
    draftFailed:     'Message drafting is temporarily unavailable',
    linkedinLogin:   'Log into LinkedIn for recruiter intel',
    limitReached:    'Upgrade to Pro for unlimited access',
  },
  pro: {
    badge:          'Pro',
    upgrade:        'Upgrade to Pro',
    price:          '₹299/mo',
    freePlan:       'Free plan',
    lookupCount:    'recruiter lookups left this month',
  },
} as const
